config/routes.rb
Rails.application.routes.draw do

  ## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'front_pages#index'

  get '/current', to: 'front_pages#currentac'
  get '/cards/credit', to: 'front_pages#creditc'
  get '/contact', to: 'front_pages#contact'
  get '/about', to: 'front_pages#about'
  get '/covid', to: 'front_pages#covid'

  get '/admin', to: 'consoles#index'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/loginsecure',   to: 'sessions#newsecure'
  post '/loginsecure',   to: 'sessions#secure'

  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/user/secure', to: 'users#secure'
  get '/user/secure', to: 'users#show'
  get '/profile', to: 'users#show'

  get 'user_admin/:id/edit_password', to: 'user_admins#password_change'
  patch 'user_admin/:id/edit_password_action', to: 'user_admins#password_change_action'


  get 'transactions/:accid', to: 'transactions#index'
  get 'transactions/:accid/:id/', to: 'transactions#show'

  get 'transfers/:accid/new', to: 'transfers#new'
  post 'transfers/:accid/new', to: 'transactions#create'

  get 'transactions/:accid/random', to: 'account_admins#index'
  patch 'transactions/:accid/random', to: 'transaction_admins#random'

  resources :accounts , :except => [:show, :delete, :new]

  resources :account_admins do
    member do
      get :delete
    end
  end

  resources :currency_admins do
    member do
      get :delete
    end
  end

  resources :user_admins do
    member do
      get :delete
    end
  end

  resources :transaction_admins do
    member do
      get :delete
    end
  end

  resources :consoles

end

app/controllers/account_admins_controller.rb
## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 

class AccountAdminsController < ApplicationController
  # Check if the User has Logged in as an Administrator
  before_action :logged_in_user_admin


  def index
    # Sort accounts by ascending order of ID
    @accounts = Account.order('id ASC')
  end

  def show
    # Check if account this ID Exists else render error page 
    @account = Account.find_by(:id=> params[:id])
    if(@account.nil?)
      @msg = "An account with this ID was unfortunately not found :("
      render("error_pages/index")
      return
    end
    # If account eith id exists then load all transactions
    @transactions = Transaction.where(account_id: @account.id).order("created_at DESC")

    # If not transactions, throw warning message
    if (@transactions.empty?)
      flash.now[:danger] = 'No transactions'
    end

    curr = Currency.find(@account.curr_id)
    total = 0
    # Calculate current balance for the account
    @transactions.each do |t|
      total += t.amount
    end

    # Credits are stored as negative values and debits as positives hence we multiply by -1
    result = -1 * total
    @balance = curr.shortname + " " + result.to_s
  end

  def new
    @account = Account.new(:curr_id => 1, :user_id => 1)
  end

  def create
    # Limit the params sent by the accounts_params method
    @account = Account.new(account_params)

    if @account.save
      redirect_to (account_admins_path)
    else
      # In case there were errors in saving
      render('new')
    end

  end

  def edit
    @account = Account.find_by(:id=> params[:id])
    if(@account.nil?)
      @msg = "An account with this ID was unfortunately not found :("
      render("error_pages/index")
    end
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to (account_admin_path(@account))
    else
      render('edit')
    end
  end

  def delete
    @account = Account.find_by(:id=> params[:id])
    if(@account.nil?)
      @msg = "An account with this ID was unfortunately not found :("
      render("error_pages/index")
    end
  end

  def destroy
    @account = Account.find(params[:id])

    @transaction = Transaction.where(:account_id => @account.id)
    @transaction.each do |trans|
      trans.destroy
    end

    @account.destroy
    redirect_to(account_admins_path)
  end

  private
    def account_params
      params.require(:account).permit(:accname, :accnumber, :sortcode, :curr_id, :user_id)
    end
end

app/helpers/account_admins_helper.rb
module AccountAdminsHelper
end

app/views/account_admins/_error_acc_admin.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Display all errors of the account being saved to the database -->
<% if @account.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@account.errors.count, "error") %>.<br>
        <ul>
            <% @account.errors.full_messages.each do |msg| %>
            <li class='text-danger'><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

app/views/account_admins/_form.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Input form fields -->
<label>Account Name</label>
<%= f.text_field(:accname, class: 'mb-2 form-control' ) %>

<label>Account Number</label>
<%= f.text_field(:accnumber, class: 'mb-2 form-control' ) %>

<label>Sort Code</label>
<%= f.text_field(:sortcode, class: 'mb-2 form-control', placeholder: "XX-XX-XX" ) %>

<label>Currency</label>
<%= collection_select(:account, :curr_id, Currency.all, :id, :shortname, {}, class: 'mb-2 form-control' ) %>

<label>User</label>
<%= collection_select(:account, :user_id, User.where(:admin => false), :id, :username,{}, class: 'mb-2 form-control' ) %>

app/views/account_admins/delete.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= account_admins_path %>">Manage Accounts</a></li>
        <li class="breadcrumb-item"><a href="#">Delete <%= @account.accname %></a></li>
    </ol>
</nav>

<div class="row mt-5">
    <div class="col-12">
        <div class="card ">
            <div class="card-header">
                <h2>Delete Account</h2>
            </div>
            <div class="card-body">
								<!-- An input form to delete an account -->
                <%= form_for(@account,:url => account_admin_path(@account) , :method => 'delete') do |f| %>

		<!-- Display the account number chosen to be deleted -->
    <p>Are you sure you want to delete this Bank Account with Number </p>
    <h3><%= @account.accnumber %> ?</h3>

    <div class="form-buttons">
      <%= f.submit "Yes, Delete this Account", class: 'btn btn-danger'  %>
    </div>

		<!-- A link to the index page -->
    <%= link_to("No, Take me back", account_admins_path, :class => 'btn btn-success') %>

  <% end %>
            </div>
        </div>
    </div>
</div>

app/views/account_admins/edit.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= account_admins_path %>">Manage Accounts</a></li>
        <li class="breadcrumb-item"><a href="#">Edit <%= @account.accname %></a></li>
    </ol>
</nav>

<div class="row mt-5">
    <div class="col-12">
        <div class="card ">
            <div class="card-header">
                <h2>Update Account</h2>
            </div>
            <div class="card-body">
								<!-- Renders the partial _error_acc_admin.html.erb -->
                <%= render 'error_acc_admin' %>

                <!-- An input form to update an account -->
                <%= form_for(@account, :url => account_admin_path(@account)) do |f| %>

								<!-- Renders the partial _form.html.erb -->
                <%= render(:partial=> 'form', :locals => {:f => f}) %>

                <div class="form-buttons">
                    <%= f.submit "Update Account", class: 'btn btn-warning'  %>
                </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/account_admins/index.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= account_admins_path %>">Manage Accounts</a></li>
    </ol>
</nav>

<div class="jumbotron">
    <h2 class="h1-responsive">Manage Accounts</h2>
    <p class="lead">Add/Edit/Delete accounts from this page.</p>
    <hr class="my-2">
    <p>Click below to add a new account.
    </p>
    <%= link_to("Add New Account", new_account_admin_path, :class => 'btn btn-success btn-lg') %>

</div>


<div class="accounts index">
    <table id="masterHolder" class="listing table table-bordered" summary="Account list">
        <!-- Table header cells -->
        <thead class="black white-text">
            <tr>
                <th>#</th>
                <th>Account Name</th>
                <th>Account Number</th>
                <th>Sort Code</th>
                <th>User Name</th>
                <th>Currency</th>
                <th>Actions</th>
            </tr>
        </thead>
        <!-- Records for the table -->
        <tbody>
            <!-- Display values for every account in the database -->
            <% @accounts.each do |account| %>
            <tr>
                <td><%= account.id %></td>
                <td><%= account.accname %></td>
                <td><%= account.accnumber %></td>
                <td><%= account.sortcode %></td>
                <td><%= User.find(account.user_id).fname %></td>
                <td><%= Currency.find(account.curr_id).shortname %></td>
                <!-- Show, edit and delete links for an account-->
                <td class="actions">
                    <a href="<%= account_admin_path(account) %>"><button type="button" class="action show btn btn-sm btn-primary">Show</button></a>
                    <a href="<%= edit_account_admin_path(account) %>"><button type="button" class="action edit btn btn-sm btn-warning">Edit</button></a>
                    <a href="<%= delete_account_admin_path(account) %>"><button type="button" class="action edit btn btn-sm btn-danger">Close</button></a>
                    <%= form_with url: "/transactions/#{account.id}/random", method: :patch, local: true  do |form| %>
                    <button type="submit " class="btn btn-sm btn-default">Create 10 Transactions</button>
                    <% end %>


                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<script>
    var dataTable = null;
    $(document).ready(function() {
        dataTable = $('#masterHolder').DataTable({
            "order": [
                [4, "asc"]
            ]
        });
        document.addEventListener("turbolinks:before-cache", function() {
            if (dataTable !== null) {
                dataTable.destroy()
                dataTable = null
            }
        })
    });
</script>

app/views/account_admins/new.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= account_admins_path %>">Manage Accounts</a></li>
        <li class="breadcrumb-item"><a href="#">New Account</a></li>
    </ol>
</nav>



<div class="row mt-5">
    <div class="col-12">
        <div class="card ">
            <div class="card-header">
                <h2>Create Account</h2>
            </div>
            <div class="card-body">
                <!-- Renders the partial _error_acc_admin.html.erb -->
                <%= render 'error_acc_admin' %>

                <!-- An input form to create a new account -->
                <%= form_for(@account, :url => account_admins_path, :method => 'post') do |f| %>

                <!-- Renders the partial _form.html.erb -->
                <%= render(:partial=> 'form', :locals => {:f => f}) %>

                <div class="form-buttons">
                    <%= f.submit "Create Account", disable_with: 'Creating Accounting...', class: 'btn btn-success' %>
                </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/account_admins/show.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= account_admins_path %>">Manage Accounts</a></li>
        <li class="breadcrumb-item"><a href="#">View <%= @account.accname %></a></li>
    </ol>
</nav>
<%
currency = Currency.find(@account.curr_id)
%>

<div class="card">
    <!-- Display values of the selected accounts -->
    <div class="card-body">
        <h5 class="card-title"><%= @account.accname %></h5>
        <p class="card-text">Number: <strong><%= @account.accnumber %></strong></p>
        <p class="card-text">Currency: <strong><%= currency.shortname %></strong></p>
        <p class="card-text">Sort-Code: <strong><%= @account.sortcode %></strong></p>
        <p class="card-text">User Name: <strong><%= User.find(@account.user_id).fname %></strong></p>
        <p class="card-text">Created: <strong><%= @account.created_at %></strong></p>
        <p class="card-text">Updated: <strong><%= @account.updated_at %></strong></p>
        <h3 id="balance">Balance: <span class="badge badge-primary"><%= @balance %></span></h3>
    </div>
</div>
<hr>


<!-- Transactions table for current account -->
<table id="masterHolder" class="table table-bordered">
    <thead class="black white-text">
        <tr>
            <th style="padding-left: 20px">Date</th>
            <th>Receiver Name</th>
            <th>Currency</th>
            <th>Credits</th>
            <th>Debits</th>
        </tr>
    </thead>

    <tbody>
        <% @transactions.each do |t| %>
        <tr>
            <th scope="row"><%= t.created_at %></th>
            <td><%= t.receiver %></td>
            <td>
                <%= currency.shortname %>
            </td>
            <!-- Displays the credit if the amount transferred is negative (gaining money)
               Multiple by -1 to represent as a positive number -->
            <td>
                <% if t.amount < 0 %>
                <%= t.amount * -1 %>
                <% else %>
                -
                <% end %>
            </td>
            <!-- Displays the debit if the amount transferred is positive (losing money) -->
            <td>
                <% if t.amount >= 0 %>
                <%= t.amount %>
                <% else %>
                -
                <% end %>
            </td>

        </tr>
        <% end %>
    </tbody>
</table>

<script>
    var dataTable = null;
    $(document).ready(function() {

        dataTable = $('#masterHolder').DataTable({
            "order": [
                [0, "desc"]
            ]
        });
        document.addEventListener("turbolinks:before-cache", function() {
            if (dataTable !== null) {
                dataTable.destroy()
                dataTable = null
            }
        })
    });
</script>