config/routes.rb
Rails.application.routes.draw do

  ## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'front_pages#index'

  get '/current', to: 'front_pages#currentac'
  get '/cards/credit', to: 'front_pages#creditc'
  get '/contact', to: 'front_pages#contact'
  get '/about', to: 'front_pages#about'
  get '/covid', to: 'front_pages#covid'

  get '/admin', to: 'consoles#index'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/loginsecure',   to: 'sessions#newsecure'
  post '/loginsecure',   to: 'sessions#secure'

  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/user/secure', to: 'users#secure'
  get '/user/secure', to: 'users#show'
  get '/profile', to: 'users#show'

  get 'user_admin/:id/edit_password', to: 'user_admins#password_change'
  patch 'user_admin/:id/edit_password_action', to: 'user_admins#password_change_action'


  get 'transactions/:accid', to: 'transactions#index'
  get 'transactions/:accid/:id/', to: 'transactions#show'

  get 'transfers/:accid/new', to: 'transfers#new'
  post 'transfers/:accid/new', to: 'transactions#create'

  get 'transactions/:accid/random', to: 'account_admins#index'
  patch 'transactions/:accid/random', to: 'transaction_admins#random'

  resources :accounts , :except => [:show, :delete, :new]

  resources :account_admins do
    member do
      get :delete
    end
  end

  resources :currency_admins do
    member do
      get :delete
    end
  end

  resources :user_admins do
    member do
      get :delete
    end
  end

  resources :transaction_admins do
    member do
      get :delete
    end
  end

  resources :consoles

end

app/controllers/currency_admins_controller.rb
## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 

class CurrencyAdminsController < ApplicationController
  before_action :logged_in_user_admin
  def index
    @currencies = Currency.order('bigname ASC')
  end

  def show
    @currency = Currency.find(params[:id])
  end

  def new
    @currency = Currency.new()
  end

  def create
    # Make a new currency with currency_params
    @currency = Currency.new(currency_params)
    if @currency.save
      redirect_to (currency_admin_path(@currency))
    else
      render('new')
    end
  end

  def edit
    @currency = Currency.find(params[:id])
  end

  def update
    # Update values of currency with currency_params
    @currency = Currency.find(params[:id])
    if @currency.update(currency_params)
      redirect_to (currency_admin_path(@currency))
    else
      render('edit')
    end
  end

  def delete
    @currency = Currency.find(params[:id])
  end

  def destroy
    @currency = Currency.find(params[:id])
    # The currency cannot be deleted if there is an account using it
    @currency.destroy unless Account.where(:curr_id => @currency.id).length > 0
    redirect_to(currency_admins_path)
  end

  private
    def currency_params
      params.require(:currency).permit(:bigname, :shortname)
    end
end

app/helpers/currency_admins_helper.rb
module CurrencyAdminsHelper
end

app/views/currency_admins/_error_cur_admin.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Check for errors -->
<% if @currency.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@currency.errors.count, "error") %>.<br>
        <ul>
        <% @currency.errors.full_messages.each do |msg| %>
        <li class='text-danger'><%= msg %></li>
        <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/currency_admins/_form.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Form fields with bigname and shortname for currency-->
<%= f.label :Big_Name %>
<%= f.text_field :bigname, class: 'mb-1 form-control' %>

<%= f.label :Shortname %>
<%= f.text_field :shortname, class: 'mb-1 form-control' %>

app/views/currency_admins/delete.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Breadcrumb trail under header -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= currency_admins_path %>">Manage Currencies</a></li>
        <li class="breadcrumb-item"><a href="#">Delete</a></li>
    </ol>
</nav>


<!-- Section: Content -->
<div class="row mt-5">
    <div class="col-12">
        <div class="card ">

            <div class="card-header">
                <h2>Delete Currency</h2>
            </div>

            <div class="card-body">
                <div class="accounts new">
                    <!-- Don't delete currency if there is an account using it-->
                    <% if Account.where(:curr_id => @currency.id).length > 0 %>
                    <div id="error_explanation">
                        <div class="alert alert-danger">
                            Cannot delete: An existing account uses this currency
                        </div>
                    </div>
                    <!-- Else, delete this currency-->
                    <% else %>
                    <%= form_for(@currency, :url => currency_admin_path(@currency) , :method => 'delete') do |f| %>

                    <p>Are you sure you want to delete this Currency?</p>
                    <h3><%= @currency.bigname %> </h3>

                    <!-- Confirm deletion-->
                    <div class="form-buttons">
                        <%= f.submit "Yes, Delete this Currency", class: 'btn btn-danger'  %>
                    </div>

                    <!--Cancel deletion-->
                    <%= link_to("No, Take me back", currency_admins_path, :class => 'btn btn-success') %>

                    <% end %>

                    <% end %>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/currency_admins/edit.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Breadcrumb trail under header -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= currency_admins_path %>">Manage Currencies</a></li>
        <li class="breadcrumb-item"><a href="#">Edit</a></li>
    </ol>
</nav>


<!-- Section: Content -->
<div class="row mt-5">
    <div class="col-12">
        <div class="card ">

            <div class="card-header">
                <h2>Update Currency</h2>
            </div>

            <div class="card-body">
                <div class="currencies new">
                    <!-- Check for errors-->
                    <%= render 'error_cur_admin' %>

                    <!-- The form for updating this currency -->
                    <%= form_for(@currency, :url => currency_admin_path(@currency)) do |f| %>
                    <!-- Partial form with currency text fields -->
                    <%= render(:partial=> 'form', :locals => {:f => f}) %>

                    <div class="form-buttons">
                        <%= f.submit "Update Currency", class: 'btn btn-warning'  %>
                    </div>

                    <% end %>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/currency_admins/index.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Breadcrumb trail under header -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= currency_admins_path %>">Manage Currencies</a></li>
    </ol>
</nav>


<!-- Section: Content -->
<div class="jumbotron">
    <h2 class="h1-responsive">Manage Currencies</h2>
    <hr class="my-2">
    <p>Click below to add a new Currency.
    </p>
    <%= link_to("Add New Currency", new_currency_admin_path, :class => 'btn btn-success btn-lg') %>
</div>

<!-- Section: Content -->
<div class="table-responsive currencies index">

    <!-- List of all currencies in the database -->
    <table id="masterHolder" class="table listing" summary="Currency List">

        <thead class="black white-text">
            <tr>
                <th>#</th>
                <th>Currency Big Name</th>
                <th>Currency Short Name</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @currencies.each do |currency| %>
            <tr>
                <td><%= currency.id %></td>
                <td><%= currency.bigname %></td>
                <td><%= currency.shortname %></td>
                <!-- Buttons for all currency_admin actions -->
                <td class="actions">
                    <a href="<%= currency_admin_path(currency) %>"><button type="button" class="action show btn btn-sm btn-primary">Show</button></a>
                    <a href="<%= edit_currency_admin_path(currency) %>"><button type="button" class="action edit btn btn-sm btn-warning">Edit</button></a>
                    <a href="<%= delete_currency_admin_path(currency) %>"><button type="button" class="action edit btn btn-sm btn-danger">Delete</button></a>
                </td>
            </tr>
            <% end %>
        </tbody>

    </table>
</div>

<script>
    var dataTable = null;
    $(document).ready(function() {

        dataTable = $('#masterHolder').DataTable({
            "order": [
                [0, "asc"]
            ]
        });
        document.addEventListener("turbolinks:before-cache", function() {
            if (dataTable !== null) {
                dataTable.destroy()
                dataTable = null
            }
        })
    });
</script>

app/views/currency_admins/new.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Breadcrumb trail under header -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= currency_admins_path %>">Manage Currencies</a></li>
        <li class="breadcrumb-item"><a href="#">New</a></li>
    </ol>
</nav>


<!-- Section: Content -->
<div class="row ">
    <div class="col-12">
        <div class="card ">

            <div class="card-header">
                <h2>Create New Currency</h2>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 offset-3">
                        <!-- Check for errors-->
                        <%= render 'error_cur_admin' %>

                        <!-- The form for making a new currency -->
                        <%= form_for(@currency, :url => currency_admins_path, :method => 'post') do |f| %>
                        <!-- Partial form with currency text fields -->
                        <%= render(:partial=> 'form', :locals => {:f => f}) %>

                        <div class="form-buttons">
                            <%= f.submit "Add Currency", class: 'btn btn-success' %>
                        </div>

                        <% end %>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/currency_admins/show.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Breadcrumb trail under header -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= currency_admins_path %>">Manage Currencies</a></li>
        <li class="breadcrumb-item"><a href="#">View</a></li>
    </ol>
</nav>


<!-- Section: Content -->
<div class="row mt-5">
    <div class="col-12">
        <div class="card ">

            <div class="card-header">
                <h2>View Currency</h2>
            </div>

            <div class="card-body">
                <div class="currencies show">
                    <!-- List details about this currency -->
                    <table class="table" summary="Currency detail view">
                        <tr>
                            <th>#</th>
                            <td><%= @currency.id %></td>
                        </tr>
                        <tr>
                            <th>Big Name</th>
                            <td><%= @currency.bigname %></td>
                        </tr>
                        <tr>
                            <th>Short Name</th>
                            <td><%= @currency.shortname %></td>
                        </tr>
                        <tr>
                            <th>Created</th>
                            <td><%= @currency.created_at %></td>
                        </tr>
                        <tr>
                            <th>Updated</th>
                            <td><%= @currency.updated_at %></td>
                        </tr>
                    </table>

                </div>
            </div>

        </div>
    </div>
</div>