config/routes.rb
Rails.application.routes.draw do

  ## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'front_pages#index'

  get '/current', to: 'front_pages#currentac'
  get '/cards/credit', to: 'front_pages#creditc'
  get '/contact', to: 'front_pages#contact'
  get '/about', to: 'front_pages#about'
  get '/covid', to: 'front_pages#covid'

  get '/admin', to: 'consoles#index'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/loginsecure',   to: 'sessions#newsecure'
  post '/loginsecure',   to: 'sessions#secure'

  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/user/secure', to: 'users#secure'
  get '/user/secure', to: 'users#show'
  get '/profile', to: 'users#show'

  get 'user_admin/:id/edit_password', to: 'user_admins#password_change'
  patch 'user_admin/:id/edit_password_action', to: 'user_admins#password_change_action'


  get 'transactions/:accid', to: 'transactions#index'
  get 'transactions/:accid/:id/', to: 'transactions#show'

  get 'transfers/:accid/new', to: 'transfers#new'
  post 'transfers/:accid/new', to: 'transactions#create'

  get 'transactions/:accid/random', to: 'account_admins#index'
  patch 'transactions/:accid/random', to: 'transaction_admins#random'

  resources :accounts , :except => [:show, :delete, :new]

  resources :account_admins do
    member do
      get :delete
    end
  end

  resources :currency_admins do
    member do
      get :delete
    end
  end

  resources :user_admins do
    member do
      get :delete
    end
  end

  resources :transaction_admins do
    member do
      get :delete
    end
  end

  resources :consoles

end

app/controllers/transaction_admins_controller.rb
## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 

class TransactionAdminsController < ApplicationController
  include TransactionAdminsHelper
  #Check if current user is admin
  before_action :logged_in_user_admin

  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      redirect_to(transaction_admins_path())
    else
      render('new')
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to(transaction_admin_path(@transaction))
    else
      render('edit')
    end
  end

  def delete
    @transaction = Transaction.find(params[:id])
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to(transaction_admins_path)
  end

  # Method Generates Random 10 Transactions + 1 Salary transaction for the selected user
  def random
    # The Acccounts of the current user is fetched
    account = Account.find(params[:accid])
    # The Current Unix Time is fetched and stored as integer
    now_unix = Time.now.to_i

    # gets a list of receivers according which currency is selected
    get_receivers(account.curr_id)

    #Create an initial deposit backdated to 10 days before
    Transaction.create(
      account: account,
      receiver: "Salary Transfer",
      amount: -5000,
      created_at: Time.at(now_unix - 864000)
    )

    # For each of the local receivers, insert the transaction with random amounts and any random date between 14 days before and a few hours before
    @receivers.each do |r|
      Transaction.create(
          account: account,
          receiver: r,
          amount: rand(10..500),
          created_at: Time.at(now_unix - rand(10000..854000))
      )
    end
    # Send back to Accounts Admins path once transactions are generated
    flash[:success] = "Random Transactions Successfully Added"
    redirect_to(account_admins_path)
    return
  end


  private
  def transaction_params
    params.require(:transaction).permit(:receiver, :amount, :account_id)
  end
end

app/helpers/transaction_admins_helper.rb
## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 

module TransactionAdminsHelper
    # Takes in the ID of the currency and return an array of local shops for fake transactions
    def get_receivers id_country
        # Common Shop Names
        common_shop_names = ["McDonalds FNB Trading LLC", "Apple Inc.",
        "Nike Inc", "Nandos FNB Company Trading LLC", "Local Store 24/7", "Uber Eats LLC"]

        if id_country == 2
            #Korean Shop Names
            specific_shop = ["Burger King Seoul", "Loteria Yeoeuido-Dong", "Maebong - Travel", "GS25"]
            @receivers = common_shop_names + specific_shop
        elsif(id_country == 5)
            #Indian Shop Names
            specific_shop = ["Big Bazaar", "Olives Khan Market",
            "Big Chill Nehru Place", "Golgappa Wala"]
            @receivers = common_shop_names + specific_shop
        elsif(id_country == 4)
            #Bulgarian Shop Names
            specific_shop = ["Grand Foods Saborna","Shtastlivetsa Sofia","Skapto Iskar","Serdika Center"]
            @receivers = common_shop_names + specific_shop
        elsif(id_country == 3)
            #Romainain Shop Names
            specific_shop = ["Profi City","Magazinul Faptelor Bune","Sushi Room Stefan 25","Spitual Monza Vatra Luminosa"]
            @receivers = common_shop_names + specific_shop
        elsif(id_country == 1)
            #British Shop Names
            specific_shop = ["Sushi Samba London","Tesco UK","Boots","Bens Cookies"]
            @receivers = common_shop_names + specific_shop
        else
            #If it is any other currency just add Common Shop Names
            specific_shop = ["Convenience Store","Masks - Local Hospital","Charity Spend - Local","Home Delivery - Convenience Store"]
            @receivers = common_shop_names + specific_shop
        end
    
    end
end

app/views/transaction_admins/_error_acc_admin.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!-- Display validation errors for transactions-->
<% if @transaction.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@transaction.errors.count, "error") %>.<br>
        <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
        <li class='text-danger'><%= msg %></li>
        <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/transaction_admins/_form.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<label>Receiver</label>
<%= f.text_field(:receiver, class: 'mb-2 form-control' ) %>

<label>Amount</label>
<%= f.text_field(:amount, class: 'mb-2 form-control' ) %>

<label>Account ID</label>
<%= f.collection_select(:account_id, Account.all, :id, :accnumber,{}, class: 'mb-2 form-control' ) %>

app/views/transaction_admins/delete.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
    <li class="breadcrumb-item"><a href="<%= transaction_admins_path %>">Manage Transactions</a></li>
    <li class="breadcrumb-item"><a href="#">Delete</a></li>
  </ol>
</nav>

<!--Display the delete form-->
<div class="row mt-5">
  <div class="col-12">
    <div class="card ">
      <div class="card-header">
        <h2>Delete Transaction</h2>
      </div>
      <div class="card-body">
        <%= form_for(@transaction,:url => transaction_admin_path(@transaction) , :method => 'delete') do |f| %>
          <p>Are you sure you want to delete this transaction </p>
          <h3><%= @transaction.id %> ?</h3>
          <div class="form-buttons">
            <%= f.submit "Yes, Delete this Transaction", class: 'btn btn-danger'  %>
          </div>
          <%= link_to("No, Take me back", transaction_admins_path, :class => 'btn btn-success') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transaction_admins/edit.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
    <li class="breadcrumb-item"><a href="<%= transaction_admins_path %>">Manage Transactions</a></li>
    <li class="breadcrumb-item"><a href="#">Edit</a></li>
  </ol>
</nav>

<!--Display the edit form-->
<div class="row mt-5">
  <div class="col-12">
    <div class="card ">
      <div class="card-header">
        <h2>Update Transaction</h2>
      </div>
      <div class="card-body">
        <!-- Displays validation errors -->
        <%= render 'error_acc_admin' %>
        <%= form_for(@transaction, :url => transaction_admin_path(@transaction), :method => "PATCH") do |f| %>
        <!--Partial for receiver, amount and account_id input-->
        <%= render(:partial => 'form', :locals => {:f => f}) %>
        <br>
        <button class="btn btn-warning btn-block" type="submit">Update Transaction</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transaction_admins/index.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
        <li class="breadcrumb-item"><a href="<%= transaction_admins_path %>">Manage Transactions</a></li>
    </ol>
</nav>

<!--Admin information and create transaction button-->
<div class="jumbotron">
    <h2 class="h1-responsive">Manage Transactions</h2>
    <p class="lead">Add/Edit/Delete transactions from this page.</p>
    <hr class="my-2">
    <p>Click below to add a new transaction/transfer.</p>
    <%= link_to("Create transaction", new_transaction_admin_path, :class => 'btn btn-success btn-lg') %>
</div>

<!--Display all transactions with show/edit/delete options-->
<table id="masterHolder" class="listing table table-bordered" summary="Account list">
    <thead class="black white-text">
        <tr>
            <th>Date</th>
            <th>Associated Account</th>
            <th>Receiver Name</th>
            <th>Currency</th>
            <th>Credits</th>
            <th>Debits</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @transactions.each do |t| %>
        <%acc = Account.find(t.account_id)%>
        <tr>
            <td style="padding-left: 20px; color: black">
                <%= link_to(t.created_at, transaction_admin_path(t)) %>
            </td>
            <td>
                <%= acc.accnumber %>
            </td>
            <td>
                <%= t.receiver %>
            </td>
            <td>
                <%= Currency.find(acc.curr_id).shortname %>
            </td>
            <!-- Credits are stored as negative values-->
            <td>
                <% if t.amount < 0 %>
                <%= t.amount * -1 %>
                <% else %>
                -
                <% end %>
            </td>
            <!--Debits are stored as positive value-->
            <td>
                <% if t.amount >= 0 %>
                <%= t.amount %>
                <% else %>
                -
                <% end %>
            </td>
            <td class="actions">
                <a href="<%= transaction_admin_path(t) %>"><button type="button" class="action show btn btn-sm btn-primary">Show</button></a>
                <a href="<%= edit_transaction_admin_path(t) %>"><button type="button" class="action edit btn btn-sm btn-warning">Edit</button></a>
                <a href="<%= delete_transaction_admin_path(t) %>"><button type="button" class="action edit btn btn-sm btn-danger">Delete</button></a>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<script>
    var dataTable = null;
    $(document).ready(function() {

        dataTable = $('#masterHolder').DataTable({
            "order": [
                [0, "desc"]
            ]
        });
        document.addEventListener("turbolinks:before-cache", function() {
            if (dataTable !== null) {
                dataTable.destroy()
                dataTable = null
            }
        })
    });
</script>

app/views/transaction_admins/new.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
    <li class="breadcrumb-item"><a href="<%= transaction_admins_path %>">Manage Transactions</a></li>
    <li class="breadcrumb-item"><a href="#">New</a></li>
  </ol>
</nav>

<!--Display the new form-->
<div class="row mt-5">
  <div class="col-12">
    <div class="card ">
      <div class="card-header">
        <h2>Create Transaction</h2>
      </div>
      <div class="card-body">
        <!-- Displays validation errors -->
        <%= render 'error_acc_admin' %>
        <%= form_for(@transaction, :url => transaction_admins_path, :method => "POST") do |f| %>
        <!--Partial for receiver, amount and account_id input-->
        <%= render(:partial => 'form', :locals => {:f => f}) %>
        <br>
        <button class="btn btn-success btn-block" type="submit">Create Transaction</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transaction_admins/show.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/admin">Admin Panel</a></li>
    <li class="breadcrumb-item"><a href="<%= transaction_admins_path %>">Manage Transactions</a></li>
    <li class="breadcrumb-item"><a href="#">View</a></li>
  </ol>
</nav>

<!--Display the transaction infromation-->
<div class="card">
  <h5 class="card-header h2">Transaction# <%=@transaction.id%></h5>
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <h4>ID: <strong><%= @transaction.id %></strong></h4>
        <hr>
      </div>

      <div class="col-12">
        <h4>Date: <strong><%= @transaction.created_at %></strong></h4>
        <hr>
      </div>

      <div class="col-12">
        <h4>Account Number: <strong><%= Account.find(@transaction.account_id).accnumber %></strong></h4>
        <hr>
      </div>

      <div class="col-12">
        <h4>Currency: <strong><%= Currency.find(Account.find(@transaction.account_id).curr_id).bigname %></strong></h4>
        <hr>
      </div>

      <div class="col-12">
        <h4>Receiver Name: <strong><%= @transaction.receiver %></strong></h4>
        <hr>
      </div>

      <div class="col-12">
        <h4>Amount: <strong><%= @transaction.amount %></strong></h4>
        <hr>
      </div>
    </div>
  </div>
</div>