config/routes.rb
Rails.application.routes.draw do

  ## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'front_pages#index'

  get '/current', to: 'front_pages#currentac'
  get '/cards/credit', to: 'front_pages#creditc'
  get '/contact', to: 'front_pages#contact'
  get '/about', to: 'front_pages#about'
  get '/covid', to: 'front_pages#covid'

  get '/admin', to: 'consoles#index'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/loginsecure',   to: 'sessions#newsecure'
  post '/loginsecure',   to: 'sessions#secure'

  delete '/logout',  to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/user/secure', to: 'users#secure'
  get '/user/secure', to: 'users#show'
  get '/profile', to: 'users#show'

  get 'user_admin/:id/edit_password', to: 'user_admins#password_change'
  patch 'user_admin/:id/edit_password_action', to: 'user_admins#password_change_action'


  get 'transactions/:accid', to: 'transactions#index'
  get 'transactions/:accid/:id/', to: 'transactions#show'

  get 'transfers/:accid/new', to: 'transfers#new'
  post 'transfers/:accid/new', to: 'transactions#create'

  get 'transactions/:accid/random', to: 'account_admins#index'
  patch 'transactions/:accid/random', to: 'transaction_admins#random'

  resources :accounts , :except => [:show, :delete, :new]

  resources :account_admins do
    member do
      get :delete
    end
  end

  resources :currency_admins do
    member do
      get :delete
    end
  end

  resources :user_admins do
    member do
      get :delete
    end
  end

  resources :transaction_admins do
    member do
      get :delete
    end
  end

  resources :consoles

end

app/controllers/transactions_controller.rb
## Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) 

class TransactionsController < ApplicationController
  before_action :logged_in_user
  # User can only see transcations linked to their user_id
  def index
    #find specified account for current user
    @account = Account.find_by(:id=> params[:accid], :user_id => @current_user.id)
    # If User tried to access another User's account, show the error page:"An account with this ID was unfortunately not found :("
    if(@account.nil?)
      @msg = "An account with this ID was unfortunately not found :("
      render("error_pages/index")
    else
      @transactions = Transaction.where(account_id: @account.id).order("created_at DESC")
      if (@transactions.empty?)
        flash.now[:danger] = 'No transactions'
      end
      @currency = Currency.find(@account.curr_id)
      total = 0
      # Calculate current balance for the account
      @transactions.each do |t|
        total += t.amount
      end
      # Credits(money granted to account) are stored as negative values
      # and debits(money taken from account) as positive numbers hence we multiply by -1 to get the balance
      result = -1 * total
      @balance = @currency.shortname + " " + result.to_s
    end
  end

  def create
    # User can only see transcations linked to their user_id
    @account = Account.find_by(:id=> params[:accid], :user_id => @current_user.id)
    @currency = Currency.find(@account.curr_id)
    # If User tried to access another User's account, show the error page:"An account with this ID was unfortunately not found :("
    if(@account.nil?)
      @msg = cc
      render("error_pages/index")
    else
      @transfer = Transaction.new(transfer_params)
      @transfer.account = @account
      if params[:transaction][:amount].to_i < 0.01
        flash.now[:danger] = "Invalid Amount Selected"
        
        render("transfers/new")
        return
      end
      # :type refers to selected money transfer type (0 - Debit, 1 - Credit)
      # Debits are stored as positive numbers and credits as negative
      if params[:type].to_i == 0
        @transfer.amount *= 1
      elsif params[:type].to_i == 1
        @transfer.amount *= -1
      else  # countermeasure if user alters html through inspect elements
        flash.now[:danger] = "Invalid Type Selected"
        render("transfers/new")
        return
      end

      if @transfer.save
        redirect_to("/transactions/#{@account.id}")
      else
        render("transfers/new")
      end
    end
  end

  public
    def transfer_params
      params.require(:transaction).permit(:amount, :receiver, :type)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper

end

app/views/transactions/index.html.erb
<!-- Authors: Ayan Ahmad (K19002255), Kevin Quah (k1921877), Jae Min An (k19034574), Daniela Stanciu (k1922053), Mihaela Peneva (k19026170) -->

<!--Display the page's path-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<%= accounts_path %>">Online Banking Portal</a></li>
        <li class="breadcrumb-item"><a href="#"><%= @account.accname %></a></li>
    </ol>
</nav>

<!--Display account information-->
<div class="card">
    <div class="card-body">
        <h5 class="card-title"><%= @account.accname %></h5>
        <p class="card-text">Number: <strong><%= @account.accnumber %></strong></p>
        <p class="card-text">Currency: <strong><%= Currency.find(@account.curr_id).shortname %></strong></p>
        <p class="card-text">Sort-Code: <strong><%= @account.sortcode %></strong></p>
        <p class="card-text">User Name: <strong><%= User.find(@account.user_id).fname %></strong></p>
        <p class="card-text">Created: <strong><%= @account.created_at %></strong></p>
        <p class="card-text">Updated: <strong><%= @account.updated_at %></strong></p>

        <a href="<%= edit_account_path(@account) %>"><button type="button" class="action edit btn btn-md btn-warning">Edit</button></a>

        <a href="/transfers/<%= @account.id  %>/new"><button type="button" class="action show btn btn-md btn-success">Transfer Money</button></a>
    </div>
</div>

<hr>

<!-- Div with balance information-->
<div id="transactions_functionality">
    <h3 id="balance">Balance: <span class="badge badge-primary"><%= @balance %></span></h3>
</div>

<br>

<!-- Transactions table for current account -->
<table id="masterHolder" class="table table-bordered">
    <thead class="black white-text">
        <tr>
            <th>Date</th>
            <th>Receiver Name</th>
            <th>Currency</th>
            <th>Credits</th>
            <th>Debits</th>
        </tr>
    </thead>

    <tbody>
        <% @transactions.each do |t| %>
        <tr>
            <th scope="row"><%= t.created_at %></th>
            <td><%= t.receiver %></td>
            <td>
                <%= @currency.shortname %>
            </td>
            <td>
                <!--Credits are stored as negative numbers-->
                <% if t.amount < 0 %>
                <%= t.amount * -1 %>
                <% else %>
                -
                <% end %>
            </td>
            <td>
                <!--Debits are stored as positive numbers-->
                <% if t.amount >= 0 %>
                <%= t.amount %>
                <% else %>
                -
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<script>
    var dataTable = null;
    $(document).ready(function() {
        dataTable = $('#masterHolder').DataTable({
            "order": [
                [0, "desc"]
            ]
        });
        document.addEventListener("turbolinks:before-cache", function() {
            if (dataTable !== null) {
                dataTable.destroy()
                dataTable = null
            }
        })
    });
</script>